[workspace]
members = [
    "client",
    "server",
    "shared"
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.19.1", features = ["dynamic_linking", "bevy_ui_widgets"] }
avian3d = { version = "0.7", features = ["serialize"] }
lightyear = { git = "https://github.com/cBournhonesque/lightyear.git", branch = "main", default-features = false, features = [
    "netcode",
    "replication",
    "prediction",
    "interpolation",
    "avian3d", 
    "udp", 
    "crossbeam",
    "input_bei",
    ]}
bevy_enhanced_input = { version = "0.26.0", features = ["serialize"]}
serde = { version = "1.0", features = ["derive"]}
rand = "0.9"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3